// app/layout.jsx

// import { SpeedInsights } from "@vercel/speed-insights/next";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";

export const metadata = {
  title: "SiapUjian | Simulasi ANBK",
  description: "Generated by create next app",
  icons: {
    icon: ["/logo4.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo4.png" />
      </head>
      <body>
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
        {/* <SpeedInsights /> */}
      </body>
    </html>
  );
}
