import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import "../../app/globals.css";

export const metadata = {
  title: "Simulasi ANBK",
  description: "Generated by create next app",
  icons: {
    icon: ["/logo4.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="logo" href="/logo4.png" />
      </head>
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
