import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import "../../app/globals.css";
import NavbarGuru from "../components/guru/NavbarGuru";

export const metadata = {
  title: "SiapUjian | Selamat datang di halaman dashboard guru",
  description: "Generated by create next app",
  icons: {
    icon: ["/logo4.png"],
  },
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="logo" href="/logo4.png" />
      </head>
      <body>
        <div className="flex flex-row">
          <NavbarGuru />
          {children}
        </div>
      </body>
    </html>
  );
}
